version: 2

updates:
  # =========================
  # Maven dependencies
  # =========================
  - package-ecosystem: "maven"
    directory: "/spring-boot-tutorial-basics"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-with-swagger"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-exception-handling"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-tutorial-soap-web-services"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-rest-services-with-unit-and-integration-tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-basic"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-versioning"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-rest-services"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-myBatis-with-h2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-jpa-hibernate-with-h2-full-stack/backend-spring-boot-react-jpa-hibernate-with-h2-full-stack"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-jwt-auth-login-logout/backend-spring-boot-react-jwt-auth-login-logout"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-crud-full-stack-with-maven/backend-spring-boot-react-crud-full-stack-with-maven"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-basic-auth-login-logout/backend-spring-boot-react-basic-auth-login-logout"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-cors-cross-origin-csrf/backend-spring-boot-react-cors-cross-origin-csrf"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-react-examples/spring-boot-react-hello-world-with-routing/backend-spring-boot-react-hello-world-with-routing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-validation"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-content-negotiation"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-tutorial-basics-configuration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-kotlin-basics-configuration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-basic-microservice/spring-boot-microservice-eureka-naming-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-basic-microservice/spring-boot-microservice-currency-conversion-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-basic-microservice/spring-boot-microservice-forex-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-jdbc-with-h2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-web-application-bootstrap-jquery"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-jpa-with-hibernate-and-h2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-with-hateoas"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-jpa-spring-data-rest"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"

  - package-ecosystem: "maven"
    directory: "/spring-boot-2-rest-service-filtering"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-major"
          